
TRUNCATE TABLE cdt.cdt_pods;
TRUNCATE TABLE cdt.cdt_pod_restarts;
TRUNCATE TABLE cdt.cdt_pod_statistics;

TRUNCATE TABLE cdt.cdt_stream_registry;

TRUNCATE TABLE cdt.cdt_meta_params;
TRUNCATE TABLE cdt.cdt_meta_dictionary;
TRUNCATE TABLE cdt.cdt_meta_suspend;

TRUNCATE TABLE cdt.cdt_stream_calls;
TRUNCATE TABLE cdt.cdt_stream_trace;
TRUNCATE TABLE cdt.cdt_stream_sql;
TRUNCATE TABLE cdt.cdt_stream_xml;

TRUNCATE TABLE cdt.cdt_stream_gc;
TRUNCATE TABLE cdt.cdt_stream_top;
TRUNCATE TABLE cdt.cdt_stream_td;
TRUNCATE TABLE cdt.cdt_stream_heap;
